version: 2.1

jobs:
  build-and-save:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - run:
          name: "Release build"
          command: "cd dino-backend && cargo build --release"
      - store_artifacts:
          name: "Save binary"
          path: ./dino-backend/target/release/dino-backend
          destination: dino-backend

workflows:
  build:
    jobs:
      - build-and-save
