version: 2.1

jobs:
  build-and-save:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: "Print libc version"
          command: "/lib/x86_64-linux-gnu/libc.so.6"
      - run: 
          name: "Install rust"
          command: "curl https://sh.rustup.rs -sSf | sh -s -- -y"

      - run:
          name: "Release build"
          command: "source $HOME/.cargo/env && cd dino-backend && cargo build --release"
      - store_artifacts:
          name: "Save binary"
          path: ./dino-backend/target/release/dino-backend
          destination: dino-backend

workflows:
  build:
    jobs:
      - build-and-save
