version: 2.1

jobs:
  build-and-save:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: 
          name: "Install rust"
          command: "curl https://sh.rustup.rs -sSf | sh -s -- -y"
      - run:
          name: "Install musl libc target"
          command: "source $HOME/.cargo/env &&
            rustup target add x86_64-unknown-linux-musl"
      - run:
          name: "Release build"
          command: "source $HOME/.cargo/env &&
            cd dino-backend &&
            cargo build --release --target=x86_64-unknown-linux-musl"
      - store_artifacts:
          name: "Save binary"
          path: ./dino-backend/target/x86_64-unknown-linux-musl/release/dino-backend
          destination: dino-backend

workflows:
  build:
    jobs:
      - build-and-save
