const spriteUrl = {
    bird1: '/assets/sprites/bird-1.png',
    bird2: '/assets/sprites/bird-2.png',
    cactusBig1: '/assets/sprites/cactus-big-1.png',
    cactusBig2: '/assets/sprites/cactus-big-2.png',
    cactusBigPair: '/assets/sprites/cactus-big-pair.png',
    cactusBigSmall: '/assets/sprites/cactus-big-small.png',
    cactusSmall1: '/assets/sprites/cactus-small-1.png',
    cactusSmall2: '/assets/sprites/cactus-small-2.png',
    cactusSmall3: '/assets/sprites/cactus-small-3.png',
    cactusSmall4: '/assets/sprites/cactus-small-4.png',
    cactusSmall5: '/assets/sprites/cactus-small-5.png',
    cactusSmall6: '/assets/sprites/cactus-small-6.png',
    cloud: '/assets/sprites/cloud.png',
    dinoDuck1: '/assets/sprites/dino-duck-1.png',
    dinoDuck2: '/assets/sprites/dino-duck-2.png',
    dinoGameOver1: '/assets/sprites/dino-game-over-1.png',
    dinoGameOver2: '/assets/sprites/dino-game-over-2.png',
    dinoJump: '/assets/sprites/dino-jump.png',
    dinoRun1: '/assets/sprites/dino-run-1.png',
    dinoRun2: '/assets/sprites/dino-run-2.png',
    ground: '/assets/sprites/ground.png',
}